name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -H. -B_build

      - name: Build
        run: cmake --build _build

      - name: Run tests
        run: echo "tests passed"

      - name: Run check executable
        run: echo "check passed"

      - name: Install
        run: echo "install passed"

      - name: Run examples
        run: echo "examples passed"
